version: "3"

services:
  api:
    build: ./api
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app/api
    command: nodemon index.js
  frontend:
    build: ./client
    depends_on:
      - api
    ports: 
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /home/node/app/client
    command: npm start
# volumes:
# configs:
# secrets:
# networks:
